# Generated by Django 5.2 on 2025-04-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treino", "0003_alter_usuario_nivel_experiencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nivel_experiencia",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="sexo",
        ),
        migrations.AddField(
            model_name="usuario",
            name="altura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="frequencia_treino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nivel_condicionamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
